# Generated by Django 2.2.3 on 2019-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('HTML', 'HTML'), ('Javascript', 'Javascript'), ('Node.js', 'Node.js'), ('React', 'React'), ('Python', 'Pythoon'), ('Data Science', 'Data Science'), ('SQL', 'SQL'), ('Java', 'Java'), ('JQuery', 'JQuery'), ('css', 'css'), ('Sass', 'Sass')], default='HTML', max_length=50)),
                ('post_body', models.TextField()),
                ('post_title', models.CharField(max_length=50)),
            ],
        ),
    ]
