# Generated by Django 2.2.3 on 2019-08-03 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_board', '0002_question_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
